### ISSUE TITLE
Add apps grouping using tag

### ISSUE THREAD

**Issue by githubsaturn** [caprover/caprover-frontend#52]
It'd be nice if users can group multiple apps/databases under one group. There are two options
- Going with a group > app solution
- Going with app > tag1, tag2, tag3 solution

The second option is more generic and allows users to have multiple ways to organize their app, e.g.,
- All apps for Project Moonshot
- All databases
- All relational instances
- All NodeJS applications
- etc....

**Comment by vohzd** [comment]
Anyone else working on this feature? I might have a crack at this (first option)

**Comment by githubsaturn** [comment]
I haven't started working on this one, if you're interested, feel free to take a stab at it. Once you have a solution in mind, please share it here so we can discuss before you build.

**Comment by nativeit** [comment]
I was just thinking about requesting and/or beginning work on a similar feature to group the one-click-apps listings as well, since the collection is currently growing at a fairly healthy clip and it may soon be a little difficult to navigate. I think using tags is the natural and simplest approach and could be employed for both the one-click-app listings as well as individuals' installed apps. 

I would only add that for the one-click-apps, a straightforward tagging convention specified in the docs would probably go a long way in preventing redundancies and promoting better organization. A single paragraph with a 2-3 plain rules would probably suffice.

I figured I'd check to see if anyone (@vohzd or @githubsaturn?) had started work on this yet? If so, is there anything I can do to help? My skillset is largely with UI design, frontend development, and fairly basic API interactions. If I find that I can make something functional along these lines, I will post back here, just let me know if anyone's made any progress so I don't cross any lines.

**Comment by githubsaturn** [comment]
I haven't looked into this yet, but it's definitely on my radar... I'll ping you when I have a better understanding of what the right approach will look like.

**Comment by marekbrze** [comment]
Maybe as the interim solution we could add simple "add to favourites" option? 

I am new to Caprover and it's frustrating to scroll the long list of apps. It would be great to be able to select some of the as favourites/star them.

**Comment by githubsaturn** [comment]
It's the top front end feature. So it'll be done soon!
